[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anproto_python"
version = "0.1.0"
description = "ANProto Python port"
requires-python = ">=3.8"
dependencies = [
    "cryptography>=40.0"
]
